apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-7gk2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zavr-tenant/rhtap-demo-app/hacbs-test-project-7gk2@sha256:f2c22e1ab9c924144459f2b4eb793c148b10c3bdbc02e1009446e596a98ed38e
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
