apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-7gk2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-7gk2
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-7gk2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-7gk2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-7gk2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zavr-tenant/rhtap-demo-app/hacbs-test-project-7gk2@sha256:2e275691c8e43019830498fb85c3143cc708beebcaccbe95b23f1b5f799c728a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
